version: "3.9"
services:

  sql-server-db:
    container_name: sql-server-db
    image: microsoft/mssql-server-linux:2017-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass!123"
      ACCEPT_EULA: "Y"
    networks:
      - network
networks:
  network:
    driver: bridge